function fig2img(fig,outFormat)
%FIG2IMG saves a MATLAB .fig file in another image format.
%
% Inputs:
%   > fig: path to *.fig file
%   > outFormat: output file format (excludes PDF and PS*).
% Outputs:
%   > none
% Other actions:
%   > Saves image file using same filename and same locaiton as input.

validFormats = { ...
    'jpeg', ...
    'png', ...
    'tiff', ...
    'tiffn', ...
    'meta', ...
    'bmpmono', ...
    'bmp', ...
    'bmp16m', ...
    'bmp256', ...
    'hdf', ...
    'pbm', ...
    'pbmraw', ...
    'pcxmono', ...
    'pcx24b', ...
    'pcx256', ...
    'pcx16', ...
    'pgm', ...
    'pgmraw', ...
    'ppm', ...
    'ppmraw', ...
    'eps', ...
    'epsc', ...
    'eps2', ...
    'epsc2', ...
    'svg'};

assert(ismember(outFormat,validFormats))

[path,name,~] = fileparts(fig);
f = openfig(fig);
truesize
% f.Units = 'normalized';
% f.OuterPosition = [0 0 1 1];

saveas(gcf,fullfile(path,name),outFormat);

close(f)

end